#!/bin/env python
#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#
# -*- coding: utf-8 -*-

from sstr import sstr
import unittest

class TestSstr(unittest.TestCase):
    
    def test_sstr(self):
        s1 = sstr("abcde")
        self.assertTrue(s1 << 0 == 'abcde', "'abcde' is expected")
        self.assertTrue(s1 >> 0 == 'abcde', "'abcde' is expected")
        self.assertTrue(s1 << 2 == 'cdeab', "'cdeab' is expected")
        self.assertTrue(s1 >> 2 == 'deabc', "'cdeab' is expected")
        self.assertTrue(s1 >> 5 == 'abcde', "'abcde' is expected")
        self.assertTrue((s1 >> 5) << 5 == 'abcde', "'abcde' is expected")

if __name__ == '__main__':
    unittest.main()
